=== Miguel935daw/Practica10LMSGI/rss_parte1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs = "http://www.w3.org/2001/XMLSchema">
    <xs:element name="rss">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="channel" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute name="version" type="xs:decimal"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="channel">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="link" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="category" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="description" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="item" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="title" type="xs:string"/>
    <xs:element name="link" type="xs:string"/>
    <xs:element name="category" type="xs:string"/>
    <xs:element name="description" type="xs:string"/>
    <xs:element name="item">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="link" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="description" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="author" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="enclosure" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="author" type="xs:string"/>
    <xs:element name="enclosure" type="xs:string"/>
</xs:schema>

=== Miguel935daw/Practica10LMSGI/ejemplo_feed.xml
<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="rss_parte1.xsd" version="2.0">
    <channel>
        <title>Me lo invento</title>
        <link></link>
        <category>Noticias</category>
        <description>Secci√≥n de Noticias</description>
        <item>
            <title>Me lo invento</title>
            <link></link>
            <description>Perico</description>
            <author>meloinvento@gmail.com</author>
            <enclosure>https://youtu.be/jW3LHUoXW9c</enclosure>
        </item>
    </channel>
</rss>
